LIB_SRC = EventLoop.cc Channel.cc Poller.cc TimerQueue.cc Timer.cc
BINARIES = test1 test2 test3 test4

all: $(BINARIES)

include ../muduo.mk

test1: test1.cc
test2: test2.cc
test3: test3.cc
test4: test4.cc
